spring:
  application:
    name: JunitTest
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: dawjxxx
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: create
        format_sql: true
    show-sql: true
    database: mysql
